config/routes.rb
Rails.application.routes.draw do
     devise_for :users


     # UserTeams Routes
     resources :user_teams

     # Teams Routes
     resources :team do
          member do
               get :events
          end

          member do
               post :event
          end

          member do
               get :tasks
          end

          member do
               post :task
          end

          member do
               get :members
          end

          member do
               post :member
          end
     end

     resources :events


     get 'home/index'

     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
     root to: "team#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
     belongs_to :user
     belongs_to :team
end

app/models/task.rb
class Task < ApplicationRecord
     belongs_to :team
     has_many :user_tasks
end

app/models/team.rb
class Team < ApplicationRecord
     has_many :user_teams
     has_many :user, through: :user_teams

     has_many :events

     validates :name, presence: true
     validates :objective, presence: true
     validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # To specify the many to many relations with the team model using UserTeam model
  has_many :user_teams
  has_many :teams, through: :user_teams

  has_many :events

  has_many :user_task

  validates :email, presence: true
  validates :encrypted_password, presence: true
end

app/models/user_task.rb
class UserTask < ApplicationRecord
     belongs_to :users
     belongs_to :tasks
end

app/models/user_team.rb
class UserTeam < ApplicationRecord
     belongs_to :user
     belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Define always auth
  before_action :authenticate_user!

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


     def new
          @event = Even.new
     end

     def create
          @event = Event.new(event_params)
          @event.date = Date.new
          @event.latitude = 15.2
          @event.longitude = 25.3
          @event.team_id = 19
          @event.user_id = 4

          respond_to do |format|
               if @event.save
                    format.html {redirect_to events_team_path, notice: 'User team was successfully created.'}
                    format.json {render :show, status: :created, location: @event}
               else
                    format.html {redirect_to team_path}
                    format.json {render json: @team.errors, status: :unprocessable_entity}
               end
          end
     end

     private
     # Event form params
     def event_params
          params.require(:event).permit(:title, :description)
     end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
     def index
          @team = current_user.teams
     end

     def new
          @team = Team.new
     end

     def create
          @team = Team.new(team_params)

          respond_to do |format|
               if @team.save
                    #format.html {redirect_to @team, notice: 'User team was successfully created.'}
                    format.html {redirect_to new_user_team_path(id: @team.id), notice: 'User team was successfully created.'}
                    format.json {render :show, status: :created, location: @team}
               else
                    format.html {render :new}
                    format.json {render json: @team.errors, status: :unprocessable_entity}
               end
          end

     end

     def show
          # To get the id of the current team
          @current_team = Team.find(params[:id])
     end

     def events
          # To get the id of the current team
          @current_team = Team.find(params[:id])
          @event = Event.where(:team_id => params[:id])
     end

     # To create a event
     def event
          @event = Event.new
          @event.title = params[:title].to_s
          @event.description = params[:description].to_s
          @event.date = Date.new
          @event.latitude = 15.2
          @event.longitude = 10.6
          @event.team_id = Team.find(params[:id]).id
          @event.user_id = current_user.id

          respond_to do |format|
               if @event.save
                    format.html {redirect_to events_team_path, notice: 'User team was successfully created.'}
                    format.json {render :show, status: :created, location: @event}
               else
                    format.html {redirect_to team_path}
                    format.json {render json: @team.errors, status: :unprocessable_entity}
               end
          end
     end

     def members
          @members = Team.find(params[:id]).user
     end

     def tasks
          # To get the id of the current team
          @current_team = Team.find(params[:id])
          @task = Task.where(:team_id => params[:id])
     end

     # To create a event
     def task
          @task = Task.new
          @task.title = params[:title].to_s
          @task.description = params[:description].to_s
          @task.date = Date.new
          @task.team_id = Team.find(params[:id]).id

          respond_to do |format|
               if @task.save
                    format.html {redirect_to tasks_team_path, notice: 'Task was successfully created.'}
                    format.json {render :show, status: :created, location: @task}
               else
                    format.html {redirect_to tasks_team_path}
                    format.json {render json: @task.errors, status: :unprocessable_entity}
               end
          end
     end

     private
          # Use callbacks to share common setup or constraints between actions.
          def set_team
               @team = Team.find(params[:id])
          end

          # Never trust parameters from the scary inte rnet, only allow the white list through.
          def team_params
               params.require(:team).permit(:name, :objective, :description)
          end

          # Event form params
          def event_params
               params.require(:event).permit(:title, :description)
          end

          # Event form params
          def task_params
               params.require(:event).permit(:title, :description, :date)
          end
end

app/controllers/user_teams_controller.rb
class UserTeamsController < ApplicationController
     def index
          @user_team = UserTeam.all
     end

     def new
          # To instance a new UserTeam
          @user_team = UserTeam.new

          @users = if params[:username]
                        User.where('name LIKE ?', "%#{params[:username]}%")
                   else
                        User.all
                   end

          @team_id = params[:id]
     end

     def create
          @user_team = UserTeam.new
          @user_team.user_id = params[:user_id_list]
          @user_team.team_id = params[:team_id]

          respond_to do |format|
               if @user_team.save
                    format.html {redirect_to team_path(:id => params[:team_id]), notice: 'User team was successfully created.'}
                    format.json {render :show, status: :created, location: @user_team}
               else
                    format.html {render :new}
                    format.json {render json: @user_team.errors, status: :unprocessable_entity}
               end
          end
     end

     private
          # Use callbacks to share common setup or constraints between actions.
          def set_team
               @user_team = UserTeam.find(params[:id])
          end

          # Never trust parameters from the scary internet, only allow the white list through.
          def team_params
               params.require(:user_team).permit(:team_id, :user_id => [])
          end

          def user_params
               params.require(:user).permit(:username)
          end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<%- if user_signed_in? %>
    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>MyWorkTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/team/events.html.erb
<div class="container">
    <nav class="nav" id="nav">
        <div class="nav__header">
            <div class="user-avatar">
                <div class="circle">
                    <div class="circle">
                        <div class="avatar"></div>
                    </div>
                </div>
            </div>
            <div class="user-data">
                <span class="user-name"><%= current_user.email %></span>
                <span class="user-job">CEO</span>
            </div>
        </div>
        <div class="nav__body">
            <ul class="menu">
                <li class="menu__item"><span class="icon-home"></span> <%= link_to 'Inicio', team_path %></li>
                <li class="menu__item"><span class="icon-chat"></span> Conversaciones</li>
                <li class="menu__item"><span class="icon-tasks"></span> <%= link_to 'Tareas', tasks_team_path %></li>
                <li class="menu__item item__selected"><span class="icon-event"></span> <%= link_to 'Eventos', events_team_path %></li>
                <li class="menu__item"><span class="icon-member"></span> <%= link_to 'Miembros', events_team_path %></li>
            </ul>
        </div>
    </nav>
    <div class="content">
        <header class="header">
            <span class="icon-menu" id="menu"></span>
            <div class="options">
                <div class="option-profile">
                    <div class="avatar-options">
                        <%- if user_signed_in? %>
                            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
                        <% end %>
                    </div>
                </div>
            </div>
        </header>
        <div class="content-main">
            <div class="container-events">
                <div class="events-action">
                    <button class="continue-button login-button add-event-button" id="addEvent">Agregar</button>
                </div>
                    <% @event.each do |event| %>
                        <div class="card card-event">
                            <div class="card-event__header">

                                <%= event.title %>
                            </div>
                            <div class="card-event__content">
                                <%= event.description %>
                                <%= event.date %>
                            </div>
                            <div class="card-event__footer">
                                <div class="event-user__image"></div>
                                <div class="event-user__username"><%= User.find(event.user_id).email %></div>
                            </div>
                        </div>
                    <% end %>
            </div>
        </div>
    </div>
</div>

<div class="container-dialog hide-element" id="container-dialog">
    <div class="add-event-dialog card">
        <div class="add-event-dialog__header">
            <div class="title title-new-team">Agregar un evento</div>
        </div>
        <div class="add-event-dialog__content">
            <%= form_tag(controller: "team", action: "event", method: "post") do |f| %>
                <div class="field">
                    <%= label_tag :Título %><br />
                    <%= text_field_tag(:title) %>
                </div>

                <div class="field">
                    <%= label_tag :Descripción %><br />
                    <%= text_field_tag(:description) %>
                </div>

                <div class="field">
                    <%= label_tag :Fecha__y__hora %><br />
                    <%= text_field_tag(:date) %>
                </div>

                <div class="actions">
                    <%= submit_tag("Guardar") %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/team/index.html.erb
<div class="container-dashboard-team">
    <div class="dashboard-team-header">
        <div class="card-profile">
            <div class="user-avatar">
                <div class="circle">
                    <div class="circle">
                        <div class="avatar"></div>
                    </div>
                </div>
            </div>
            <div class="user-data">
                <span class="user-name"><%= current_user.email %></span>
                <span class="user-job">CEO</span>
                <div class="button edit-profile-button">Editar Perfil</div>
            </div>
        </div>
    </div>

    <div class="dashboard-team-body">

        <div class="container-team">
            <%= link_to new_team_path, class: "card card-team-space add-team-card" do %>
                <div class="center-elements-column">
                    <span class="add-icon">+</span>
                    <span>Crear espacio de trabajo</span>
                </div>
            <% end %>
            <% @team.each do |user_team| %>
                <div class="card card-team-space ">
                    <div class="header__card-team">
                        <span class="team-name"><%= user_team.name %></span>
                    </div>
                    <div class="body__card-team">
                        <div class="team-members"><span class="quantity">18</span> miembros</div>
                        <button class="visit-team"><%= link_to 'Visitar', user_team %></button>
                    </div>
                </div>
                <!--<tr>-->
                <!--<td></td>-->
                <!--<td><%= %></td>-->
                <!--<td><%= link_to 'Show', user_team %></td>-->
                <!--<td><%= link_to 'Edit', edit_user_team_path(user_team) %></td>-->
                <!--<td><%= link_to 'Destroy', user_team, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
                <!--</tr>-->
            <% end %>
        </div>
    </div>
</div>

<%- if user_signed_in? %>
    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
<% end %>

app/views/team/members.html.erb
<div class="container">
    <nav class="nav" id="nav">
        <div class="nav__header">
            <div class="user-avatar">
                <div class="circle">
                    <div class="circle">
                        <div class="avatar"></div>
                    </div>
                </div>
            </div>
            <div class="user-data">
                <span class="user-name"><%= current_user.email %></span>
                <span class="user-job">CEO</span>
            </div>
        </div>
        <div class="nav__body">
            <ul class="menu">
                <li class="menu__item"><span class="icon-home"></span> <%= link_to 'Inicio', team_path %></li>
                <li class="menu__item"><span class="icon-chat"></span> Conversaciones</li>
                <li class="menu__item"><span class="icon-tasks"></span> <%= link_to 'Tareas', tasks_team_path %></li>
                <li class="menu__item"><span class="icon-event"></span> <%= link_to 'Eventos', events_team_path %></li>
                <li class="menu__item item__selected"><span class="icon-member"></span> <%= link_to 'Miembros', members_team_path %></li>
            </ul>
        </div>
    </nav>
    <div class="content">
        <header class="header">
            <span class="icon-menu" id="menu"></span>
            <div class="options">
                <div class="option-profile">
                    <div class="avatar-options">
                        <%- if user_signed_in? %>
                            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
                        <% end %>
                    </div>
                </div>
            </div>
        </header>
        <div class="content-main">
            <div class="container-events">
                <div class="events-action">
                    <button class="continue-button login-button add-event-button" id="addEvent">Agregar</button>
                </div>
                <% @members.each do |member| %>
                    <div class="card card-event">
                        <div class="card-event__header">
                            <%= member.email %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="container-dialog hide-element" id="container-dialog">
    <div class="add-event-dialog card">
        <div class="add-event-dialog__header">
            <div class="title title-new-team">Agregar un nuevo miembro</div>
        </div>
        <div class="add-event-dialog__content">
            <%= form_tag(controller: "team", action: "event", method: "post") do |f| %>
                <div class="field">
                    <%= label_tag :Título %><br />
                    <%= text_field_tag(:title) %>
                </div>

                <div class="field">
                    <%= label_tag :Descripción %><br />
                    <%= text_field_tag(:description) %>
                </div>

                <div class="field">
                    <%= label_tag :Fecha__y__hora %><br />
                    <%= text_field_tag(:date) %>
                </div>

                <div class="actions">
                    <%= submit_tag("Guardar") %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/team/new.html.erb
<div class="artistic-container">

    <div class="circle-background circle-background--medium"></div>
    <div class="circle-background circle-background--big"></div>

    <div class="card card-new-team">
        <div class="card-new-team__header center-elements">
            <span class="title title-new-team">Crear nuevo espacio de trabajo</span>
        </div>
        <div class="card-new-team__content">
            <%= form_for @team, url: {action: "create"}, html: {class: "new-team-form"} do |f| %>
                <div class="field">
                    <%= f.label :Nombre %><br />
                    <%= f.text_field :name, autofocus: true %>
                </div>

                <div class="field">
                    <%= f.label :Objetivo %><br />
                    <%= f.text_area :objective, autofocus: true %>
                </div>

                <div class="field">
                    <%= f.label :Descripción %><br />
                    <%= f.text_area :description %>
                </div>

                <div class="actions">
                    <%= f.submit "Crear Espacio", class: "login-button" %>
                </div>
            <% end %>
        </div>

    </div>
</div>

app/views/team/show.html.erb
<div class="container">
    <nav class="nav" id="nav">
        <div class="nav__header">
            <div class="user-avatar">
                <div class="circle">
                    <div class="circle">
                        <div class="avatar"></div>
                    </div>
                </div>
            </div>
            <div class="user-data">
                <span class="user-name"><%= current_user.email %></span>
                <span class="user-job">CEO</span>
            </div>
        </div>
        <div class="nav__body">
            <ul class="menu">
                <li class="menu__item item__selected"><span class="icon-home"></span> <%= link_to 'Inicio', team_path %></li>
                <li class="menu__item"><span class="icon-chat"></span> Conversaciones</li>
                <li class="menu__item"><span class="icon-tasks"></span> <%= link_to 'Tareas', tasks_team_path %></li>
                <li class="menu__item"><span class="icon-event"></span> <%= link_to 'Eventos', events_team_path %></li>
                <li class="menu__item"><span class="icon-member"></span> <%= link_to 'Miembros', members_team_path %></li>
            </ul>
        </div>
    </nav>
    <div class="content">
        <header class="header">
            <span class="icon-menu" id="menu"></span>
            <div class="options">
                <div class="option-profile">
                    <div class="avatar-options">
                        <%- if user_signed_in? %>
                            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
                        <% end %>
                    </div>
                </div>
            </div>
        </header>
        <div class="content-main">

        </div>
    </div>
</div>

app/views/team/tasks.html.erb
<div class="container">
    <nav class="nav" id="nav">
        <div class="nav__header">
            <div class="user-avatar">
                <div class="circle">
                    <div class="circle">
                        <div class="avatar"></div>
                    </div>
                </div>
            </div>
            <div class="user-data">
                <span class="user-name"><%= current_user.email %></span>
                <span class="user-job">CEO</span>
            </div>
        </div>
        <div class="nav__body">
            <ul class="menu">
                <li class="menu__item"><span class="icon-home"></span> <%= link_to 'Inicio', team_path %></li>
                <li class="menu__item"><span class="icon-chat"></span> Conversaciones</li>
                <li class="menu__item item__selected"><span class="icon-tasks"></span> <%= link_to 'Tareas', tasks_team_path %></li>
                <li class="menu__item"><span class="icon-event"></span> <%= link_to 'Eventos', events_team_path %></li>
                <li class="menu__item"><span class="icon-member"></span> <%= link_to 'Miembros', members_team_path %></li>
            </ul>
        </div>
    </nav>
    <div class="content">
        <header class="header">
            <span class="icon-menu" id="menu"></span>
            <div class="options">
                <div class="option-profile">
                    <div class="avatar-options">
                        <%- if user_signed_in? %>
                            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
                        <% end %>
                    </div>
                </div>
            </div>
        </header>
        <div class="content-main">
            <div class="container-events">
                <div class="events-action">
                    <button class="continue-button login-button add-event-button" id="addEvent">Agregar</button>
                </div>
                <% @task.each do |task| %>
                    <div class="card card-task">
                        <div class="card-task__header">
                            <%= task.title %>
                        </div>
                        <div class="card-task__content">
                            <%= task.description %>
                            <%= task.date %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>


<div class="container-dialog hide-element" id="container-dialog">
    <div class="add-event-dialog card">
        <div class="add-event-dialog__header">
            <div class="title title-new-team">Agregar tarea</div>
        </div>
        <div class="add-event-dialog__content add-team-dialog__content">
            <%= form_tag(controller: "team", action: "event", method: "post") do |f| %>
                <div class="field">
                    <%= label_tag :Título %><br />
                    <%= text_field_tag(:title) %>
                </div>

                <div class="field">
                    <%= label_tag :Descripción %><br />
                    <%= text_field_tag(:description) %>
                </div>

                <div class="field">
                    <%= label_tag :Fecha__y__hora %><br />
                    <%= text_field_tag(:date) %>
                </div>

                <div class="field">
                    <%= label_tag :Asignar__tarea %><br />
                    <%= text_field_tag(:date) %>
                </div>

                <div class="actions">
                    <%= submit_tag("Guardar") %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/user_teams/new.html.erb
<div class="artistic-container">

    <div class="circle-background circle-background--medium"></div>
    <div class="circle-background circle-background--big"></div>

    <div class="card card-new-team">
        <div class="card-new-team__header center-elements">
            <span class="title title-new-team">Agregar miembros</span>
        </div>
        <div class="card-new-team__content">
            <div class="filter-container">
                <div class="header-filter">
                    <label for="user-filter" class="label-filter">Elegir miembros</label>
                    <input type="text" id="user-filter" class="input-filter">
                </div>
                <div class="filter-list-container">
                    <ul class="list-users" id="list-filter-user">
                        <% @users.each do |user| %>
                            <li class="list__item" id="<%= user.id %>"
                                onclick="
                                    addUserToTeam('<%= user.email %>', <%= user.id %>);
                                ">
                                <span><%= user.email %></span></li>
                        <% end %>

                    </ul>
                </div>
                <div class="selected-users" id="selected-users">
                </div>
            </div>
        </div>

        <div class="card-new-team__footer">
            <div class="continue-button" id="continue">Continuar</div>
        </div>

    </div>
</div>

<script>

    var selectedUsers = document.getElementById('selected-users');

    function addUserToTeam(email, id) {


        /**
         * To create dynamically node elements with pure js and show in the
         * list selected user.
         *
         * @type {Element}
         */
        var selectedUsersItem = document.createElement("div");
            selectedUsersItem.className ="selected-users__item";
            selectedUsersItem.id = id;

            var userInfo = document.createElement("div");
                userInfo.className = "user-info";

                var selectedUserAvatar = document.createElement("div");
                selectedUserAvatar.className = "selected-user__avatar";

                var selectedUserEmail = document.createElement("div");
                selectedUserEmail.className = "selected-user__email";
                selectedUserEmail.innerHTML = email;

                //Set nodes
                userInfo.appendChild(selectedUserAvatar);
                userInfo.appendChild(selectedUserEmail);

            var userDelete = document.createElement("div");
                userDelete.className = "user-delete";
                userDelete.onclick = function () {
                    selectedUsersItem.parentNode.removeChild(selectedUsersItem);


                };

                var deleteIcon = document.createElement("span");
                deleteIcon.className = "delete-icon";
                deleteIcon.innerHTML = "X";

                userDelete.appendChild(deleteIcon);

        //Set nodes
        selectedUsersItem.appendChild(userInfo);
        selectedUsersItem.appendChild(userDelete);

        //Set all the nodes inside the selected users container
        selectedUsers.appendChild(selectedUsersItem);
    }

    /**
     * When the continue button is clicked send the elements to the controller
     */
    var continueButton = document.getElementById('continue');

    // Event clicked handler
    continueButton.addEventListener('click', function () {
        getSelectedUserId();
    });


    /**
     * Iterate the item selected and get the id.
     * Then pass to the controller using Ajax
     */
    function getSelectedUserId() {
        var userSelectedItems = document.querySelectorAll('.selected-users__item');
        var listId = [];
        var teamId = <%= @team_id %>;

        for (var i = 0; i < userSelectedItems.length; i++){
            listId.push(parseInt(userSelectedItems[i].getAttribute('id')));

        }

        if(listId.length > 0){
            $.ajax({
                url : "/user_teams",
                type : "post",
                data : { user_id_list: JSON.stringify(listId[0]), team_id : JSON.stringify(teamId) },
                success: function () {
                    alert("Hola");
                }
            });
        } else {
            alert("Debes elegir al menos un miembro");
        }

        //alert("user_id: " + listId[0] + " - - - - team_id: " + teamId);
    }
</script>